module.exports = {
    mappingHeader:"Provide a mapping for each of the columns of the spreadsheet previewed below. Check indicators above to know which spreadsheets are complete.",
    "column-selection":"Choose a column from the active spreadsheet previewed below to start mapping",
    type:"What type of data is provided by this column. Ex: a class type will produce individuals, while a data property will provide information for and individual",
    name:"The name of the property that describes the data produced by this column. The options are conditioned by the selected type.",
    valueType:"Value type of the node ",
    naming_scheme:"How to call the individual generated by this column, the buttons and select form can be used to create dynamic naming based on the line-wise data in the spreadsheet. The autoincrement button is used to generate a unique individual for each line in the spreadsheet, the value button is used to add the cell value to the name. The reference column select form can be used to add the value of another column to the naming scheme based on the current line.",
    objectProperty:"Select the object property to link this individual to another individual (node)",
    dataProperty:"Data property text",
    refSelector:"Reference Selector information text."
};