module.exports = {
    "missing-class":"Please select a class to start mapping, if the class you are mapping is not in the list, you can write it and add it, by pressing enter on the input once it is written.",
    mappingHeader:"Provide a mapping for each of the columns of the spreadsheet previewed below. Check indicators above to know which spreadsheets are complete. Generally the columns are data data properties of some class. For each worksheet create the appropriate classes to be linked to the data properties.",
    "column-selection":"Choose a column from the active spreadsheet previewed below to start mapping",
    type:"What type of data is provided by this column. Ex: a class type will produce individuals, while a data property will provide information for and individual",
    name:"The name of the property that describes the data produced by this column. The options are conditioned by the selected type.",
    valueType:"Value type of the node ",
    naming_scheme:"How to call the individual generated by this column, the buttons and select form can be used to create dynamic naming based on the line-wise data in the spreadsheet. The autoincrement button is used to generate a unique individual for each line in the spreadsheet, the value button is used to add the cell value to the name. The reference column select form can be used to add the value of another column to the naming scheme based on the current line.",
    objectProperty:"Select the object property to link this individual to another individual (node)",
    dataProperty:"Data property text",
    "object-property-selection":"Choose an object property from the active spreadsheet previewed below. If no options are active please add the appropriate classes. This selection does not constrain the selection of object properties.",
    "object-property-selection-inferred":"Choose an object property from the active spreadsheet previewed below. If no options are active please add the appropriate classes. This selection only displays inferred properties based on the ontology.",
    "data-property-selection":"Choose a data property from the active spreadsheet previewed below. If no options are active please map a column as a data property.",
    refSelector:"Optional! Reference Selector can be used to add the value of another column to the naming scheme."
};